// File: lib/products.ts

export const allProducts = [
  {
    id: "coconut-shell-charcoal-briquettes",
    name: "Coconut Shell Charcoal Briquettes",
    category: "Bioenergy",
    image: "/images/bricket.png",
    badge: "Premium",
    moq: "10 Tons",
    description: "Premium 100% Pure Indonesian Coconut Shell Charcoal Briquettes, Export Quality, Sustainable Energy. Manufactured exclusively from selected mature coconut shells, our briquettes produce superior heat, low ash, and longer burning time with no smoke, odor, or sparks.",
    specifications: [
      { label: "Shape & Size", value: "Cubic/Hexagonal/Cylindrical/Dome ± 15-40 mm" },
      { label: "Moisture Content", value: "± 5 - 8%" },
      { label: "Ash Content", value: "± 2 - 8%" },
      { label: "Fixed Carbon", value: "± 70 - 85%" },
      { label: "Calorific Value", value: "± 5000 - 8000 kcl/kg" },
      { label: "Burning Time", value: "± 1 - 2.5 hours" },
    ],
  },
  {
    id: "cocopeat",
    name: "Cocopeat",
    category: "Bioenergy",
    image: "/images/cocopeat.png",
    badge: "Sourced Direct",
    moq: "10 Tons",
    description: "Premium Indonesia Cocopeat - the perfect natural growing medium. Carefully processed from mature coconut fiber, our cocopeat is 100% natural, renewable, and eco-friendly - a sustainable choice trusted by professional farmers. Double washed and buffered, sterile, pathogen-free.",
    specifications: [
      { label: "Form", value: "Compressed blocks 5kg, Bales 15 - 25 kg" },
      { label: "Moisture Content", value: "± 10 - 20%" },
      { label: "Electrical Conductivity", value: "± 0.5 - 1.0 mS/cm" },
      { label: "Volume", value: "± 60 - 85 liter/5kg" },
      { label: "pH", value: "5.5 - 7.0" },
    ],
  },
  {
    id: "cocofiber",
    name: "Cocofiber",
    category: "Bioenergy",
    image: "/images/cocofiber.png",
    badge: "Premium",
    moq: "10 Tons",
    description: "Superior quality Cocofiber made from selected mature coconut fibers. The fibers are long, strong, and elastic thanks to high natural lignin content. Resistant to saltwater, heat, and mold - ideal for growing media, slope stabilization, or premium product manufacturing.",
    specifications: [
      { label: "Moisture Content", value: "± 15 - 20% (Maximum 20%)" },
      { label: "Purity", value: "± 2 - 5%" },
      { label: "Dust Content", value: "± 2 - 5%" },
      { label: "Color", value: "Golden yellow / Bright brown / Natural brown" },
      { label: "Weight per Bale", value: "80 - 120 kg" },
    ],
  },
  {
    id: "cardamom",
    name: "Cardamom",
    category: "Spices",
    image: "/images/kopilaga.png",
    badge: "Sourced Direct",
    moq: "500 Kg",
    description: "From Indonesia's lush tropical mountains grows superior quality cardamom. Naturally processed and carefully dried to preserve warm, fresh, sweet, and slightly spicy aromatic profile. Rich in essential oils and 1,8-cineole content.",
    specifications: [
      { label: "Moisture Content", value: "± 8 - 12%" },
      { label: "Essential Oil Content", value: "± 2.0 - 4.5%" },
      { label: "Purity", value: "± 0.5 - 2%" },
      { label: "Color", value: "Shiny green, light brown" },
    ],
  },
  {
    id: "javanese-turmeric",
    name: "Javanese Turmeric",
    category: "Spices",
    image: "/images/temulawak.png",
    badge: "Premium",
    moq: "1 Ton",
    description: "Premium Javanese Turmeric rhizome (King of Herbs) from local farmers, naturally dried to preserve bioactive compounds. Extraordinary benefits with high curcuminoid and xanthorrhizol content to support liver health, digestion, and antioxidant properties.",
    specifications: [
      { label: "Moisture Content", value: "± 8 - 14%" },
      { label: "Essential Oil Content", value: "± 1 - 2%" },
      { label: "Curcuminoid Content", value: "± 1 - 2.5%" },
      { label: "Purity", value: "± 0.5 - 2%" },
      { label: "Slice Size", value: "± 3 - 6 mm" },
    ],
  },
  {
    id: "cloves",
    name: "Cloves",
    category: "Spices",
    image: "/images/cengkeh.png",
    badge: "Premium",
    moq: "500 Kg",
    description: "Premium cloves from Indonesian soil (Maluku, Sulawesi, Java). Hand-picked and naturally dried. Beautiful reddish-brown color with strong aroma and high essential oil and eugenol content.",
    specifications: [
      { label: "Moisture Content", value: "± 8 - 13%" },
      { label: "Essential Oil Content", value: "± 12 - 20%" },
      { label: "Purity", value: "± 0.5 - 2%" },
      { label: "Color", value: "Reddish-brown, Shiny black, Standard brown" },
    ],
  },
  {
    id: "robusta-coffee",
    name: "Robusta Coffee",
    category: "Agriculture",
    image: "/images/kopi.png",
    badge: "Sourced Direct",
    moq: "2 Tons",
    description: "High-quality Robusta coffee beans from the fertile lowlands of Indonesia. Our beans deliver bold, full-bodied flavor with high caffeine content, ideal for espresso blends and instant coffee manufacturing.",
    specifications: [
      { label: "Grade", value: "EK1 / Grade 4" },
      { label: "Altitude", value: "400-800 MASL" },
      { label: "Moisture Content", value: "12-13%" },
      { label: "Defect Count", value: "≤ 60 per 300g" },
      { label: "Processing", value: "Natural / Washed" },
    ],
  },
]

export type Product = typeof allProducts[number]